---
apiVersion:
kind: 
metadata:
  name: 
  labels:
    app: 
spec: 
  replicas: 
  selector:
    matchLabels:
      app:  
  template:
    metadata:
      labels:
        app: 
    spec: 
      containers:
      - name: 
        image:  
        ports:
        - containerPort: 
