---
apiVersion: 
kind: 
metadata:
  name: 
  labels:
    app:
spec: 
  replicas: 
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app:
    spec: 
      containers:
      - name: 
        image: 
        ports:
        - containerPort: 

--- 
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 
      targetPort: 
...